export default {
  data() {
    return {
      default_model: {
        'componentType': 'TEXT',
        'componentTypeDesc': '',
        'fieldName': '',
        'fieldInnerName': '',
        'fieldOrder': null,
        'fieldStatus': 'OPEN',
        'fieldExtra': '{"template":{"text":null,"status":0},"validateCommand":{"LENGTH":60}}',
        'fieldSummary': '',
        'isBuiltin': 'YES',
        'description': '',
        'editable': 'YES',
        'required': false,
        'isDraggable': false,
        'isLine': false
      },
      tables: [],
      tables1: [
        {
          'id': 92297,
          'orgId': '7f245313a9154c82af5cc160a667de30',
          'moduleId': 'COMPANY',
          'componentType': 'TEXT',
          'refKey': null,
          'componentTypeDesc': '文本框',
          'fieldName': '公司注册名',
          'fieldInnerName': '公司注册名',
          'fieldKey': 'key76',
          'fieldOrder': null,
          'fieldStatus': 'OPEN',
          'fieldExtra': '{"template":{"text":null},"validateCommand":{"LENGTH":601}}',
          'fieldSummary': '公司注册名',
          'createdAt': '2018-03-16 11:39:46',
          'isBuiltin': 'YES',
          'description': '公司全称',
          'editable': 'YES',
          'required': false,
          'isDraggable': false,
          'isLine': false
        },
        {
          'id': 137755,
          'orgId': '7f245313a9154c82af5cc160a667de30',
          'moduleId': 'COMPANY',
          'componentType': 'RADIO',
          'refKey': null,
          'componentTypeDesc': '单选',
          'fieldName': '测试1',
          'fieldInnerName': null,
          'fieldKey': 'key353',
          'fieldOrder': null,
          'fieldStatus': 'OPEN',
          'fieldExtra': '{"template":{"items":[{"choose":false,"content":"c1"},{"choose":false,"content":"c2"}]},"validateCommand":{}}',
          'fieldSummary': 'c1,c2',
          'createdAt': '2020-04-29 18:47:27',
          'isBuiltin': 'NO',
          'description': '22',
          'editable': 'YES',
          'required': false,
          'isDraggable': false,
          'isLine': false
        },
        {
          'id': 137756,
          'orgId': '7f245313a9154c82af5cc160a667de30',
          'moduleId': 'COMPANY',
          'componentType': 'CHECK_BOX',
          'refKey': null,
          'componentTypeDesc': '多选',
          'fieldName': '测试2',
          'fieldInnerName': null,
          'fieldKey': 'key354',
          'fieldOrder': null,
          'fieldStatus': 'OPEN',
          'fieldExtra': '{"template":{"items":[{"choose":false,"content":"c1"},{"choose":true,"content":"c2"},{"choose":true,"content":"c3"}]},"validateCommand":{}}',
          'fieldSummary': 'c1,c2,c3',
          'createdAt': '2020-05-06 15:30:53',
          'isBuiltin': 'NO',
          'description': null,
          'editable': 'YES',
          'required': false,
          'isDraggable': false,
          'isLine': false
        },
        {
          'id': 137757,
          'orgId': '7f245313a9154c82af5cc160a667de30',
          'moduleId': 'COMPANY',
          'componentType': 'DATE',
          'refKey': null,
          'componentTypeDesc': '日期',
          'fieldName': '测试3',
          'fieldInnerName': null,
          'fieldKey': 'key355',
          'fieldOrder': null,
          'fieldStatus': 'OPEN',
          'fieldExtra': '{"template":{"date":null,"type":"month"},"validateCommand":{"DATE_FORMAT":"yyyy-MM"}}',
          'fieldSummary': '测试3',
          'createdAt': '2020-05-06 17:02:35',
          'isBuiltin': 'NO',
          'description': null,
          'editable': 'YES',
          'required': false,
          'isDraggable': false,
          'isLine': false
        },
        {
          'id': 137759,
          'orgId': '7f245313a9154c82af5cc160a667de30',
          'moduleId': 'COMPANY',
          'componentType': 'NUMBER',
          'refKey': null,
          'componentTypeDesc': '数字',
          'fieldName': '测试4',
          'fieldInnerName': null,
          'fieldKey': 'key357',
          'fieldOrder': null,
          'fieldStatus': 'OPEN',
          'fieldExtra': '{"template":{"number":null,"decimals":9},"validateCommand":{"DECIMALS":9}}',
          'fieldSummary': '测试4',
          'createdAt': '2020-05-06 18:13:48',
          'isBuiltin': 'NO',
          'description': null,
          'editable': 'YES',
          'required': false,
          'isDraggable': false,
          'isLine': false
        },
        {
          'id': 137760,
          'orgId': '7f245313a9154c82af5cc160a667de30',
          'moduleId': 'COMPANY',
          'componentType': 'CURRENCY',
          'refKey': null,
          'componentTypeDesc': '金额',
          'fieldName': '测试5',
          'fieldInnerName': null,
          'fieldKey': 'key358',
          'fieldOrder': null,
          'fieldStatus': 'OPEN',
          'fieldExtra': '{"template":{"number":null,"unit":"元","decimals":6,"ccy":null},"validateCommand":{"DECIMALS":6}}',
          'fieldSummary': '测试5',
          'createdAt': '2020-05-06 18:54:33',
          'isBuiltin': 'NO',
          'description': null,
          'editable': 'YES',
          'required': false,
          'isDraggable': false,
          'isLine': false
        },
        {
          'id': 137761,
          'orgId': '7f245313a9154c82af5cc160a667de30',
          'moduleId': 'COMPANY',
          'componentType': 'TEL',
          'refKey': null,
          'componentTypeDesc': '电话',
          'fieldName': '测试6',
          'fieldInnerName': null,
          'fieldKey': 'key359',
          'fieldOrder': null,
          'fieldStatus': 'OPEN',
          'fieldExtra': '{"template":{"tel":null},"validateCommand":{}}',
          'fieldSummary': '测试6',
          'createdAt': '2020-05-06 19:01:36',
          'isBuiltin': 'NO',
          'description': null,
          'editable': 'YES',
          'required': false,
          'isDraggable': false,
          'isLine': false
        },
        {
          'id': 137762,
          'orgId': '7f245313a9154c82af5cc160a667de30',
          'moduleId': 'COMPANY',
          'componentType': 'EMAIL',
          'refKey': null,
          'componentTypeDesc': '邮箱',
          'fieldName': '测试7',
          'fieldInnerName': null,
          'fieldKey': 'key360',
          'fieldOrder': null,
          'fieldStatus': 'OPEN',
          'fieldExtra': '{"template":{"email":null},"validateCommand":{}}',
          'fieldSummary': '测试7',
          'createdAt': '2020-05-06 19:08:56',
          'isBuiltin': 'NO',
          'description': null,
          'editable': 'YES',
          'required': false,
          'isDraggable': false,
          'isLine': false
        },
        {
          'id': 137763,
          'orgId': '7f245313a9154c82af5cc160a667de30',
          'moduleId': 'COMPANY',
          'componentType': 'TEXTAREA',
          'refKey': null,
          'componentTypeDesc': '多行文本框',
          'fieldName': '测试8',
          'fieldInnerName': null,
          'fieldKey': 'key361',
          'fieldOrder': null,
          'fieldStatus': 'OPEN',
          'fieldExtra': '{"template":{"text":null},"validateCommand":{"LENGTH":500}}',
          'fieldSummary': '测试8',
          'createdAt': '2020-05-07 10:09:12',
          'isBuiltin': 'NO',
          'description': null,
          'editable': 'YES',
          'required': false
        }
      ],
      test: [
        {
          'isListView': '1',
          'isReadonly': '1',
          'componentId': '1',
          'fieldExtra': '{"template":{"text":null,"status":0},"validateCommand":{"LENGTH":60}}',
          'fieldName': '名称',
          'defaultValue': '0',
          'validationRule': '',
          'precision': 0,
          'fieldDesc': '名称字段描述',
          'isNotnull': '',
          'isLock': '0',
          'propertyCode': 'field1',
          'componentName': '文本框',
          'id': 1,
          'componentValueType': 'TEXT',
          'fieldId': 0,
          'componentType': 'componentClassiftiy',
          'isRequired': '1',
          'helpText': '',
          'componentCode': 'ZJ1',
          'fieldCode': 'NAME',
          'isFormView': '',
          'length': 256,
          'isPrimaryKey': '',
          'isSingleUpdate': '0',
          'propertyName': '名称',
          'tenantId': 0,
          'fieldType': 'VARCHAR',
          'isLine': false
        }, {
          'isListView': '0',
          'isReadonly': '0',
          'componentId': '1',
          'fieldExtra': '{"template":{"type":"tel","status":0},"validateCommand":{"LENGTH":60}}',
          'fieldName': '联系方式',
          'defaultValue': '0',
          'validationRule': '',
          'precision': 0,
          'fieldDesc': '联系方式字段描述',
          'isNotnull': '',
          'isLock': '1',
          'propertyCode': 'field2',
          'componentName': '文本框',
          'id': 2,
          'componentValueType': 'TEXT',
          'fieldId': 0,
          'componentType': 'componentClassiftiy',
          'isRequired': '0',
          'helpText': '',
          'componentCode': 'ZJ1',
          'fieldCode': 'TEL',
          'isFormView': '',
          'length': 16,
          'isPrimaryKey': '',
          'isSingleUpdate': '0',
          'propertyName': '联系方式',
          'tenantId': 0,
          'fieldType': 'VARCHAR',
          'isLine': false
        }
      ],
      dialogVisible: false,
      dialogVisible1: false,
      itemData: null,
      moduleField: null
    }
  },
  created() {}
}
